# docker-compose.yml
version: "3.9"

services:
  backend:
    build: ./backend
    environment:
      - PORT=3000
    ports:
      - "3001:3000"
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
